### ISSUE TITLE
DBの状態遷移難しい

### ISSUE THREAD

**Issue by nt16145** [tiro-finale/g1-VBA-PHP#5]

**Comment by tetsunae** [comment]
げんき？

**Comment by itomoya** [comment]
やばい

**Comment by itomoya** [comment]
わからん

**Comment by tetsunae** [comment]
なにするか今から把握しなきゃいけない

**Comment by nt16145** [comment]
とりあえず追加の処理と更新の処理と削除の処理はフローを分けたほうがよさそう

**Comment by itomoya** [comment]
追加の処理はさっきのでいいかな

**Comment by itomoya** [comment]
更新と削除を新たに作る感じで

**Comment by nt16145** [comment]
> 追加の処理はさっきのでいいかな
いいとおもう

**Comment by nt16145** [comment]
> 更新と削除を新たに作る感じで

方針はそんな感じで

**Comment by itomoya** [comment]
更新と削除の情報もCSVファイルから読み取る感じ？

**Comment by itomoya** [comment]
> 更新と削除の情報もCSVファイルから読み取る感じ？

自分で言っといてあれだけどめんどくさそう

**Comment by tetsunae** [comment]
そこはおれらで決めれそうだから何でもいい説

**Comment by nt16145** [comment]
多分一番開発しやすいのにしておいたほうが...

**Comment by itomoya** [comment]
スタート→情報の読み込み→DB接続→操作って感じで追加の処理は書いた

**Comment by nt16145** [comment]
それを追加、修正、削除別で書けばよさそう

**Comment by nt16145** [comment]
> それを追加、修正、削除別で書けばよさそう

具体的な処理は実装するときに考えればいいし

**Comment by itomoya** [comment]
じゃあそれで書きます7
